background {
    monitor =
	color = rgba(0, 0, 0)
}

general {
    hide_cursor = true
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 15%, 5%
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    placeholder_text =
    fail_text =

    # input box appearance
    outline_thickness = 2
    fade_on_empty = false
    outer_color = rgb(ffffff)
    check_color = rgb(0, 255, 0)
    fail_color = rgb(255, 0, 0)

    # input box positioning
    position = 0, -20
    halign = center
    valign = center
    
    # dots appearance
    font_color = rgb(255, 255, 255)
    rounding = 0
    dots_rounding = 0
    dots_spacing = 0.3
}

