general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/terencezeng/Pictures/Wallpapers/kimi_no_na_wa.jpg
}

animations {
    enabled = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.9)
    font_size = 75
    font_family = Iosevka Nerd Font
    position = 4%, -4%
    halign = left
    valign = top
}

input-field {
    monitor =
    size = 10%, 4%
    inner_color = rgba(0, 0, 0, 0.5)

    blur_passes = 2
    blur_size = 5

    placeholder_text =
    fail_text =

    # input box appearance
    outline_thickness = 2
    fade_on_empty = false
    outer_color = rgb(ffffff)
    check_color = rgb(0, 255, 0)
    fail_color = rgb(255, 0, 0)

    # input box positioning
    position = 0, 50 
    halign = center
    valign = bottom
    
    # dots appearance
    font_color = rgb(255, 255, 255)
    rounding = 0
    dots_rounding = 0
    dots_spacing = 0.3
}

